---
- name: Ensure group "panda" exists
  group:
    name: panda
    state: present

- name: Add the user 'panda' with a bash shell, in group 'panda' and 'sudo'
  user:
    name: panda
    state: present
    shell: /bin/bash
    groups: panda,sudo

- name: Set authorized key taken from file
  authorized_key:
    user: panda
    state: present
    key: "{{ lookup('file', '/home/vagrant/.ssh/authorized_keys') }}"